"""Initial migration

Revision ID: a91484a01ed6
Revises: 
Create Date: 2025-12-25 18:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a91484a01ed6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_reliability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('OPENAI', 'CLAUDE', 'GEMINI', 'DEEPSEEK', 'GROQ', 'COHERE', name='llmprovider'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('false_positive_rate', sa.Float(), nullable=True),
    sa.Column('false_negative_rate', sa.Float(), nullable=True),
    sa.Column('response_time_avg_ms', sa.Float(), nullable=True),
    sa.Column('availability_rate', sa.Float(), nullable=True),
    sa.Column('total_votes', sa.Integer(), nullable=True),
    sa.Column('correct_predictions', sa.Integer(), nullable=True),
    sa.Column('total_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('last_calibration', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_reliability_provider'), 'provider_reliability', ['provider'], unique=True)
    op.create_table('scan_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('input_preview', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scan_request_hash', 'scan_requests', ['input_hash'], unique=False)
    op.create_index('idx_scan_request_type_created', 'scan_requests', ['request_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_scan_requests_created_at'), 'scan_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_scan_requests_input_hash'), 'scan_requests', ['input_hash'], unique=False)
    op.create_index(op.f('ix_scan_requests_request_type'), 'scan_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_scan_requests_session_id'), 'scan_requests', ['session_id'], unique=False)
    op.create_index(op.f('ix_scan_requests_user_id'), 'scan_requests', ['user_id'], unique=False)
    op.create_table('agent_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('requested_action', sa.JSON(), nullable=False),
    sa.Column('requested_scope', sa.JSON(), nullable=True),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.Column('authorized_at', sa.DateTime(), nullable=True),
    sa.Column('authorized_by', sa.String(length=255), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_result', sa.JSON(), nullable=True),
    sa.Column('execution_error', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('safety_flags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_action_agent_created', 'agent_actions', ['agent_id', 'created_at'], unique=False)
    op.create_index('idx_agent_action_authorized', 'agent_actions', ['authorized', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_actions_action_type'), 'agent_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_agent_actions_agent_id'), 'agent_actions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_actions_authorized'), 'agent_actions', ['authorized'], unique=False)
    op.create_index(op.f('ix_agent_actions_created_at'), 'agent_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_actions_session_id'), 'agent_actions', ['session_id'], unique=False)
    op.create_table('council_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_request_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('final_verdict', sa.String(length=50), nullable=False),
    sa.Column('consensus_score', sa.Float(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('votes', sa.JSON(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('dissenting_opinions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['scan_request_id'], ['scan_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_council_decision_request', 'council_decisions', ['scan_request_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_council_decisions_scan_request_id'), 'council_decisions', ['scan_request_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_request_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('DETECTED', 'REVIEWED', 'RESOLVED', 'FALSE_POSITIVE', name='incidentstatus'), nullable=False),
    sa.Column('severity', sa.Enum('SAFE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('module_type', sa.Enum('PROMPT_INJECTION', 'OUTPUT_SAFETY', 'DEEPFAKE_DETECTION', 'AGENT_CONTROL', 'DATA_PRIVACY', 'DECEPTION_DETECTION', 'GOVERNANCE', name='moduletype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attack_type', sa.String(length=100), nullable=True),
    sa.Column('affected_systems', sa.JSON(), nullable=True),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('human_reviewer', sa.String(length=255), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scan_request_id'], ['scan_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_incident_module_created', 'incidents', ['module_type', 'created_at'], unique=False)
    op.create_index('idx_incident_status_severity', 'incidents', ['status', 'severity', 'created_at'], unique=False)
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_module_type'), 'incidents', ['module_type'], unique=False)
    op.create_index(op.f('ix_incidents_scan_request_id'), 'incidents', ['scan_request_id'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_request_id', sa.UUID(), nullable=False),
    sa.Column('module_type', sa.Enum('PROMPT_INJECTION', 'OUTPUT_SAFETY', 'DEEPFAKE_DETECTION', 'AGENT_CONTROL', 'DATA_PRIVACY', 'DECEPTION_DETECTION', 'GOVERNANCE', name='moduletype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('SAFE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('false_positive_probability', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['scan_request_id'], ['scan_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_risk_score_module_level', 'risk_scores', ['module_type', 'risk_level', 'created_at'], unique=False)
    op.create_index('idx_risk_score_request_module', 'risk_scores', ['scan_request_id', 'module_type'], unique=False)
    op.create_index(op.f('ix_risk_scores_module_type'), 'risk_scores', ['module_type'], unique=False)
    op.create_index(op.f('ix_risk_scores_risk_level'), 'risk_scores', ['risk_level'], unique=False)
    op.create_index(op.f('ix_risk_scores_scan_request_id'), 'risk_scores', ['scan_request_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('log_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action_created', 'audit_logs', ['action_type', 'created_at'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_incident_id'), 'audit_logs', ['incident_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_log_hash'), 'audit_logs', ['log_hash'], unique=True)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_table('individual_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('council_decision_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.Enum('OPENAI', 'CLAUDE', 'GEMINI', 'DEEPSEEK', 'GROQ', 'COHERE', name='llmprovider'), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('provider_weight', sa.Float(), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('signals_detected', sa.JSON(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['council_decision_id'], ['council_decisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('council_decision_id', 'provider', name='uq_vote_decision_provider')
    )
    op.create_index('idx_vote_provider_created', 'individual_votes', ['provider', 'created_at'], unique=False)
    op.create_index(op.f('ix_individual_votes_council_decision_id'), 'individual_votes', ['council_decision_id'], unique=False)
    op.create_index(op.f('ix_individual_votes_provider'), 'individual_votes', ['provider'], unique=False)
    op.create_table('module_fingerprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('risk_score_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('fingerprint_type', sa.String(length=50), nullable=False),
    sa.Column('pattern_hash', sa.String(length=64), nullable=False),
    sa.Column('pattern_data', sa.JSON(), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fingerprint_type_hash', 'module_fingerprints', ['fingerprint_type', 'pattern_hash'], unique=False)
    op.create_index(op.f('ix_module_fingerprints_pattern_hash'), 'module_fingerprints', ['pattern_hash'], unique=False)
    op.create_index(op.f('ix_module_fingerprints_risk_score_id'), 'module_fingerprints', ['risk_score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_module_fingerprints_risk_score_id'), table_name='module_fingerprints')
    op.drop_index(op.f('ix_module_fingerprints_pattern_hash'), table_name='module_fingerprints')
    op.drop_index('idx_fingerprint_type_hash', table_name='module_fingerprints')
    op.drop_table('module_fingerprints')
    op.drop_index(op.f('ix_individual_votes_provider'), table_name='individual_votes')
    op.drop_index(op.f('ix_individual_votes_council_decision_id'), table_name='individual_votes')
    op.drop_index('idx_vote_provider_created', table_name='individual_votes')
    op.drop_table('individual_votes')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_log_hash'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_incident_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_action_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_risk_scores_scan_request_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_risk_level'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_module_type'), table_name='risk_scores')
    op.drop_index('idx_risk_score_request_module', table_name='risk_scores')
    op.drop_index('idx_risk_score_module_level', table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_scan_request_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_module_type'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_index('idx_incident_status_severity', table_name='incidents')
    op.drop_index('idx_incident_module_created', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_council_decisions_scan_request_id'), table_name='council_decisions')
    op.drop_index('idx_council_decision_request', table_name='council_decisions')
    op.drop_table('council_decisions')
    op.drop_index('idx_agent_action_authorized', table_name='agent_actions')
    op.drop_index('idx_agent_action_agent_created', table_name='agent_actions')
    op.drop_table('agent_actions')
    op.drop_index(op.f('ix_scan_requests_user_id'), table_name='scan_requests')
    op.drop_index(op.f('ix_scan_requests_session_id'), table_name='scan_requests')
    op.drop_index(op.f('ix_scan_requests_request_type'), table_name='scan_requests')
    op.drop_index(op.f('ix_scan_requests_input_hash'), table_name='scan_requests')
    op.drop_index(op.f('ix_scan_requests_created_at'), table_name='scan_requests')
    op.drop_index('idx_scan_request_type_created', table_name='scan_requests')
    op.drop_index('idx_scan_request_hash', table_name='scan_requests')
    op.drop_table('scan_requests')
    op.drop_index(op.f('ix_provider_reliability_provider'), table_name='provider_reliability')
    op.drop_table('provider_reliability')
    # ### end Alembic commands ###
