name: Hourly Commit

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Commit and push
        run: |
          date > .github/.keep_active
          git config --global user.name "HOLYKEYZ"
          git config --global user.email "ayandajoseph390@gmail.com"
          git add .github/.keep_active
          git commit -m "chore: hourly update"
          git push
